apiVersion: v1
kind: Pod
metadata:
  namespace: wordpress
  name: wordpress-exporter
  labels:
    app: wordpress-exporter
spec:
  volumes:
    - name: wordpress
      persistentVolumeClaim:
        claimName: wordpress
        readOnly: true
    - name: wordpress-db
      persistentVolumeClaim:
        claimName: data-wordpress-mariadb-0
        readOnly: true
  containers:
    - name: wordpress-exporter
      image: imasug/disk-usage-exporter
      args:
        - /data/wordpress
        - /data/wordpress-db
      volumeMounts:
        - name: wordpress
          mountPath: /data/wordpress
        - name: wordpress-db
          mountPath: /data/wordpress-db
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-exporter
spec:
  selector:
    app: wordpress-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
