apiVersion: v1
kind: Pod
metadata:
  namespace: wordpress
  name: wordpress-exporter
  labels:
    app: wordpress-exporter
spec:
  volumes:
    persistentVolumeClaim:
      claimName: wordpress
      readOnly: true
  containers:
    - name: wordpress-exporter
      image: imasug/disk-usage-exporter
      args:
        - /data/wordpress
      volumeMounts:
        - name: wordpress
          mountPath: /data/wordpress
