apiVersion: v1
kind: Pod
metadata:
  namespace: wordpress
  name: wordpress-exporter
  labels:
    app: wordpress-exporter
spec:
  containers:
    - name: wordpress-exporter
      image: imasug/disk-usage-exporter
      args:
        - /tmp
